#!/usr/bin/env bash
# Update package information
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Create a new Nginx configuration file
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo service nginx restart
