#!/usr/bin/env bash
# Configures a new Ubuntu machine

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

echo "server {
     listen 80;
     listen [::]:80;

     root /var/www/html;
     index index.html;

     server_name _;

     location /redirect_me {
     	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }

     error_page 404 /404.html;

     location / {
	 try_files \$uri \$uri/ =404;
     }
}" | sudo tee /etc/nginx/sites-available/default

sudo sed -i "/server_name / a  add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo service nginx restart
