#!/usr/bin/env bash
# custom configuration 

sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create a new Nginx configuration file
echo "server {
     listen 80;
     listen [::]:80;

     root /var/www/html;
     index index.html;

     server_name _;

     location /redirect_me {
     	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }

     error_page 404 /404.html;

     location / {
	 try_files \$uri \$uri/ =404;
     }
}" | sudo tee /etc/nginx/sites-available/default

sudo sed -i "/server_name / a  add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# Restart Nginx service to apply changes
sudo service nginx restart
