#!/usr/bin/env bash
# Installs HAProxy with these configs:

apt-get install -y software-properties-common
sudo apt-get install -y haproxy
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 438926-web-01 100.25.212.86:80 check
   server 438926-web-02 100.	25.171.34:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start

