#!/usr/bin/env bash
#start from 1 to 10 displays 4 and then bad luck from China for the 4th loop iteration and displays 9 and then bad luck from Japan for the 9th loop iteration

i=1

while [ $i -le 20 ]
do
	echo $i

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	i=$((i+1))
done
