#!/usr/bin/env bash
# Revert the ip for localhost to 127.0.0.2 and facebook to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
echo "8.8.8.8    facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
